### ISSUE TITLE
fplot - graph code not running

### ISSUE THREAD

**Issue by julianasr36** [Flavjack/GerminaR#9]
I've been trying to figure out why I can not generate the graphs using the code provided. I tested the code in the example and it has the same issue, showing: "Error in fplot(data = plotdt, type = "bar", x = "temp", y = "grp", group = "nacl",  : unused argument (ylimits = c(0, 120, 20))". Can you solve this issue? Thanks!

**Comment by Flavjack** [comment]
Helo @julianasr36, I'm not able to reproduce the same problem,
Could you please update the package?
Or you could check the following vignette: https://germinar.inkaverse.com/articles/GerminaR.html
Please let me know any updates

**Comment by julianasr36** [comment]
The code on the vignette ran perfectly. Thanks!!
